FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .
# docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/app 47237d437fa1
# docker run 47237d437fa1 npm run test
# docker-compose down && docker-compose up --build
# docker-run -it <docker-it> npm run test   // override the command